-- FIX NODE CLLIENT ISSUES
ALTER USER 'imgstats_user' IDENTIFIED WITH mysql_native_password BY '123';
FLUSH PRIVILEGES;

/***CREATING ALL TABLES*/
CREATE TABLE stats (
  id INT unsigned PRIMARY KEY AUTO_INCREMENT NOT NULL,
  fileName varchar(500) NULL,
  action varchar(40) NULL,
  time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);